apiVersion: v1
kind: Service
metadata:
  name: url-shortener-lb
spec:
  type: LoadBalancer
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # ✅ Must match containerPort
